site_name: simpPRU
site_author: Vedant Paranjape
site_description: "Documentation for simPRU language used to program TI's PRU found on BeagleBoards"
site_url: https://simppru.readthedocs.io/
repo_url: https://github.com/VedantParanjape/simpPRU

theme:
    name: material
    features:
        - tabs
    palette:
            scheme: preference

nav:
    - Home: index.md
    - Usage: 
        - "simpPRU": usage/usage-simppru.md
        - "simpPRU-console": usage/usage-simppru-console.md
    - "Language Reference": 
        - "Language Syntax": language-reference/language.md
        - "Input/Output functions": language-reference/io.md
    - Examples: 
        - "Digital Read": examples/digital_read.md
        - "Digital Write": examples/digital_write.md
        - "Delay": examples/delay.md
        - "LED Blink": examples/led_blink.md
        - "Hardware Counter": examples/read_counter.md
        - "LED Blink using while loop": examples/led_blink_while.md
        - "LED Blink using for loop": examples/led_blink_for.md
        - "LED Blink using hardware counter as delay": examples/led_blink_counter.md
        - "HCSR04 Distance Sensor example": examples/hcsr04_sensor.md
        - "LED Blink with button control": examples/led_blink_button.md
        - "Using RPMSG to communicate with ARM core": examples/rpmsg_example.md
        - "Using RPMSG to implement a simple calculator on PRU": examples/rpmsg_pru_calculator.md
        - "Sending state of button using RPMSG": examples/button_click_rpmsg.md
        - "HCSR04 Distance Sensor example (sending distance data to ARM using RPMSG)": examples/hcsr04_example_rpmsg.md

    - Installation: 
        - "Build from source": install/build.md
        - "Install": install/install.md
    - About: 
        - "About Me": about/about.md
        - "License": about/license.md

markdown_extensions:
  - admonition
  - codehilite    
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.arithmatex